M48
; DRILL file {KiCad (6.0.2)} date Wed Nov 16 09:28:05 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-16T09:28:05-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
%
G90
G05
T1
X3.3858Y-2.9134
X3.3858Y-4.6063
X4.4882Y-2.9134
X4.4882Y-4.6063
T0
M30
